let tab = [
    {name: "mucha",         chances: 1,             rarity: "legendary",    id: "c1",             photo: "../img/cards/kartaMucha.png"      },
    {name: "smierc",        chances: 1,             rarity: "cursed",       id: "c2",             photo: "../img/cards/kartaSmierc.png"     },
    {name: "nierychly",     chances: 10,            rarity: "epic",         id: "c3",             photo: "../img/cards/kartaNierychly.png"  },
    {name: "sobczak",       chances: 10,            rarity: "epic",         id: "c4",             photo: "../img/cards/kartaSobczak.png"    },
    {name: "graczyk",       chances: 10,            rarity: "epic",         id: "c5",             photo: "../img/cards/kartaGraczyk.png"    },
    {name: "korzen",        chances: 10,            rarity: "epic",         id: "c6",             photo: "../img/cards/kartaKorzen.png"     },
    {name: "libner",        chances: 25,            rarity: "rare",         id: "c7",             photo: "../img/cards/kartaLibner.png"     },
    {name: "mgr",           chances: 25,            rarity: "rare",         id: "c8",             photo: "../img/cards/kartaMgr.png"        },
    {name: "musial",        chances: 60,            rarity: "common",       id: "c9",             photo: "../img/cards/kartaMusial.png"     },
    {name: "ciborowski",    chances: 60,            rarity: "common",       id: "c10",            photo: "../img/cards/kartaCiborowski.png" },
    {name: "pulit",         chances: 60,            rarity: "common",       id: "c11",            photo: "../img/cards/kartaPulit.png"      },
    {name: "majewska",      chances: 60,            rarity: "common",       id: "c12",            photo: "../img/cards/kartaMajewska.png"   },
    {name: "mazurek",       chances: 60,            rarity: "common",       id: "c13",            photo: "../img/cards/kartaMazurek.png"    },
]